<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CMC.TS.COFF.DMS.Biz.Model\CMC.TS.COFF.DMS.Biz.Model.csproj" />
    <ProjectReference Include="..\CMC.TS.COFF.DMS.Data\CMC.TS.COFF.DMS.Data.csproj" />
  </ItemGroup>

</Project>
